name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir ~/.m2
          echo "<settings><servers><server><id>github</id><username>jaraya81</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
      run: mvn -B package --file pom.xml
